apiVersion: v2
name: active-inventory
description: A Helm chart for deploying the active inventory service with multiple environment variables
type: application
version: 1.5.0
appVersion: "1.5.0"
keywords:
  - active-inventory
  - inventory
  - application
  - container
  - deployment
maintainers:
  - name: support@avesha.io
    email: support@avesha.io
home: https://avesha.io
sources:
  - https://github.com
icon: https://via.placeholder.com/150x150.png?text=ActiveInventory
annotations:
  category: Application
  licenses: Apache-2.0
