apiVersion: v2
name: k8s-mcp
description: A Helm chart for deploying the Kubernetes MCP (Model Context Protocol) service with multiple environment variables
type: application
version: 1.4.0
appVersion: "1.4.0"
keywords:
  - k8s-mcp
  - kubernetes
  - mcp
  - model-context-protocol
  - application
  - container
  - deployment
maintainers:
  - name: support@avesha.io
    email: support@avesha.io
home: https://avesha.io
sources:
  - https://github.com
icon: https://via.placeholder.com/150x150.png?text=K8SMCP
annotations:
  category: Application
  licenses: Apache-2.0 