apiVersion: v2
name: infra-agent
description: A Helm chart for deploying the infrastructure agent service with multiple environment variables
type: application
version: 1.2.0
appVersion: "1.2.0"
keywords:
  - infra-agent
  - infrastructure
  - agent
  - monitoring
  - application
  - container
  - deployment
maintainers:
  - name: support@avesha.io
    email: support@avesha.io
home: https://avesha.io
sources:
  - https://github.com
icon: https://via.placeholder.com/150x150.png?text=InfraAgent
annotations:
  category: Application
  licenses: Apache-2.0 