apiVersion: v2
name: oke-mcp
description: A Helm chart for deploying the Oracle Cloud (OKE) MCP (Model Context Protocol) service
type: application
version: 1.5.0
appVersion: "1.5.0"
keywords:
  - oke-mcp
  - oracle-cloud
  - oci
  - oke
  - mcp
  - model-context-protocol
  - application
  - container
  - deployment
maintainers:
  - name: support@avesha.io
    email: support@avesha.io
home: https://avesha.io
sources:
  - https://github.com
icon: https://via.placeholder.com/150x150.png?text=OKEMCP
annotations:
  category: Application
  licenses: Apache-2.0
