{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "obliq-unified-ui.fullname" . }}
  labels:
    {{- include "obliq-unified-ui.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "obliq-unified-ui.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  # Ingress rules removed - no external ingress for this service
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
{{- end }} 