apiVersion: v2
name: obliq-unified-ui
description: A Helm chart for deploying the Avesha unified UI service with multiple environment variables
type: application
version: 1.5.0
appVersion: "1.5.0"
keywords:
  - obliq-unified-ui
  - ui
  - frontend
  - web
  - application
  - container
  - deployment
maintainers:
  - name: support@avesha.io
    email: support@avesha.io
home: https://avesha.io
sources:
  - https://github.com
icon: https://via.placeholder.com/150x150.png?text=AveshaUI
annotations:
  category: Application
  licenses: Apache-2.0 