apiVersion: v2
name: aws-ec2-cloudwatch-alarms
description: A Helm chart for deploying the AWS EC2 CloudWatch alarms service with multiple environment variables
type: application
version: 1.3.0
appVersion: "1.3.0"
keywords:
  - aws-ec2-cloudwatch-alarms
  - aws
  - ec2
  - cloudwatch
  - alarms
  - monitoring
  - application
  - container
  - deployment
maintainers:
  - name: support@avesha.io
    email: support@avesha.io
home: https://avesha.io
sources:
  - https://github.com
icon: https://via.placeholder.com/150x150.png?text=EC2CloudWatch
annotations:
  category: Application
  licenses: Apache-2.0
