{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hitl-manager.fullname" . }}
  labels:
    {{- include "hitl-manager.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "hitl-manager.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
