apiVersion: v2
name: auto-remediation
description: A Helm chart for deploying the auto remediation service with multiple environment variables
type: application
version: 1.0.0
appVersion: "1.4.0"
keywords:
  - auto-remediation
  - remediation
  - automation
  - application
  - container
  - deployment
maintainers:
  - name: support@avesha.io
    email: support@avesha.io
home: https://avesha.io
sources:
  - https://github.com
icon: https://via.placeholder.com/150x150.png?text=AutoRemediation
annotations:
  category: Application
  licenses: Apache-2.0 