apiVersion: v2
name: incident-manager
description: A Helm chart for deploying the incident manager service with multiple environment variables
type: application
version: 1.4.0
appVersion: "1.4.0"
keywords:
  - incident-manager
  - incident
  - management
  - application
  - container
  - deployment
maintainers:
  - name: support@avesha.io
    email: support@avesha.io
home: https://avesha.io
sources:
  - https://github.com
icon: https://via.placeholder.com/150x150.png?text=IncidentManager
annotations:
  category: Application
  licenses: Apache-2.0 