apiVersion: v2
name: orchestrator
description: A Helm chart for deploying a single container application with multiple environment variables
type: application
version: 1.4.0
appVersion: "1.4.0"
keywords:
  - application
  - container
  - deployment
maintainers:
  - name: support@avesha.io
    email: support@avesha.io
home: https://avesha.io
sources:
  - https://github.com
icon: https://via.placeholder.com/150x150.png?text=Orchestrator
annotations:
  category: Application
  licenses: Apache-2.0 