apiVersion: v2
name: hitl-manager
description: A Helm chart for deploying the Human-in-the-Loop (HITL) manager service with multiple environment variables
type: application
version: 1.4.0
appVersion: "1.4.0"
keywords:
  - hitl-manager
  - human-in-the-loop
  - hitl
  - management
  - application
  - container
  - deployment
maintainers:
  - name: support@avesha.io
    email: support@avesha.io
home: https://avesha.io
sources:
  - https://github.com
icon: https://via.placeholder.com/150x150.png?text=HITLManager
annotations:
  category: Application
  licenses: Apache-2.0
